import React from "react";
import { PrismLight as SyntaxHighlighter } from "react-syntax-highlighter";
import { darcula } from "react-syntax-highlighter/dist/cjs/styles/prism";

import abnf from "react-syntax-highlighter/dist/cjs/languages/prism/abnf";
import actionscript from "react-syntax-highlighter/dist/cjs/languages/prism/actionscript";
import ada from "react-syntax-highlighter/dist/cjs/languages/prism/ada";
import agda from "react-syntax-highlighter/dist/cjs/languages/prism/agda";
import al from "react-syntax-highlighter/dist/cjs/languages/prism/al";
import antlr4 from "react-syntax-highlighter/dist/cjs/languages/prism/antlr4";
import apacheconf from "react-syntax-highlighter/dist/cjs/languages/prism/apacheconf";
import apex from "react-syntax-highlighter/dist/cjs/languages/prism/apex";
import apl from "react-syntax-highlighter/dist/cjs/languages/prism/apl";
import applescript from "react-syntax-highlighter/dist/cjs/languages/prism/applescript";
import aql from "react-syntax-highlighter/dist/cjs/languages/prism/aql";
import arduino from "react-syntax-highlighter/dist/cjs/languages/prism/arduino";
import arff from "react-syntax-highlighter/dist/cjs/languages/prism/arff";
import asciidoc from "react-syntax-highlighter/dist/cjs/languages/prism/asciidoc";
import asm6502 from "react-syntax-highlighter/dist/cjs/languages/prism/asm6502";
import asmatmel from "react-syntax-highlighter/dist/cjs/languages/prism/asmatmel";
import aspnet from "react-syntax-highlighter/dist/cjs/languages/prism/aspnet";
import autohotkey from "react-syntax-highlighter/dist/cjs/languages/prism/autohotkey";
import autoit from "react-syntax-highlighter/dist/cjs/languages/prism/autoit";
import avisynth from "react-syntax-highlighter/dist/cjs/languages/prism/avisynth";
import bash from "react-syntax-highlighter/dist/cjs/languages/prism/bash";
import basic from "react-syntax-highlighter/dist/cjs/languages/prism/basic";
import batch from "react-syntax-highlighter/dist/cjs/languages/prism/batch";
import bbcode from "react-syntax-highlighter/dist/cjs/languages/prism/bbcode";
import bicep from "react-syntax-highlighter/dist/cjs/languages/prism/bicep";
import birb from "react-syntax-highlighter/dist/cjs/languages/prism/birb";
import bison from "react-syntax-highlighter/dist/cjs/languages/prism/bison";
import bnf from "react-syntax-highlighter/dist/cjs/languages/prism/bnf";
import brainfuck from "react-syntax-highlighter/dist/cjs/languages/prism/brainfuck";
import brightscript from "react-syntax-highlighter/dist/cjs/languages/prism/brightscript";
import bro from "react-syntax-highlighter/dist/cjs/languages/prism/bro";
import bsl from "react-syntax-highlighter/dist/cjs/languages/prism/bsl";
import c from "react-syntax-highlighter/dist/cjs/languages/prism/c";
import cfscript from "react-syntax-highlighter/dist/cjs/languages/prism/cfscript";
import chaiscript from "react-syntax-highlighter/dist/cjs/languages/prism/chaiscript";
import cil from "react-syntax-highlighter/dist/cjs/languages/prism/cil";
import clike from "react-syntax-highlighter/dist/cjs/languages/prism/clike";
import clojure from "react-syntax-highlighter/dist/cjs/languages/prism/clojure";
import cmake from "react-syntax-highlighter/dist/cjs/languages/prism/cmake";
import cobol from "react-syntax-highlighter/dist/cjs/languages/prism/cobol";
import coffeescript from "react-syntax-highlighter/dist/cjs/languages/prism/coffeescript";
import concurnas from "react-syntax-highlighter/dist/cjs/languages/prism/concurnas";
import coq from "react-syntax-highlighter/dist/cjs/languages/prism/coq";
import cpp from "react-syntax-highlighter/dist/cjs/languages/prism/cpp";
import crystal from "react-syntax-highlighter/dist/cjs/languages/prism/crystal";
import csharp from "react-syntax-highlighter/dist/cjs/languages/prism/csharp";
import cshtml from "react-syntax-highlighter/dist/cjs/languages/prism/cshtml";
import csp from "react-syntax-highlighter/dist/cjs/languages/prism/csp";
import css from "react-syntax-highlighter/dist/cjs/languages/prism/css";
import csv from "react-syntax-highlighter/dist/cjs/languages/prism/csv";
import cypher from "react-syntax-highlighter/dist/cjs/languages/prism/cypher";
import d from "react-syntax-highlighter/dist/cjs/languages/prism/d";
import dart from "react-syntax-highlighter/dist/cjs/languages/prism/dart";
import dataweave from "react-syntax-highlighter/dist/cjs/languages/prism/dataweave";
import dax from "react-syntax-highlighter/dist/cjs/languages/prism/dax";
import dhall from "react-syntax-highlighter/dist/cjs/languages/prism/dhall";
import diff from "react-syntax-highlighter/dist/cjs/languages/prism/diff";
import django from "react-syntax-highlighter/dist/cjs/languages/prism/django";
import docker from "react-syntax-highlighter/dist/cjs/languages/prism/docker";
import dot from "react-syntax-highlighter/dist/cjs/languages/prism/dot";
import ebnf from "react-syntax-highlighter/dist/cjs/languages/prism/ebnf";
import editorconfig from "react-syntax-highlighter/dist/cjs/languages/prism/editorconfig";
import eiffel from "react-syntax-highlighter/dist/cjs/languages/prism/eiffel";
import ejs from "react-syntax-highlighter/dist/cjs/languages/prism/ejs";
import elixir from "react-syntax-highlighter/dist/cjs/languages/prism/elixir";
import elm from "react-syntax-highlighter/dist/cjs/languages/prism/elm";
import erb from "react-syntax-highlighter/dist/cjs/languages/prism/erb";
import erlang from "react-syntax-highlighter/dist/cjs/languages/prism/erlang";
import etlua from "react-syntax-highlighter/dist/cjs/languages/prism/etlua";
import factor from "react-syntax-highlighter/dist/cjs/languages/prism/factor";
import flow from "react-syntax-highlighter/dist/cjs/languages/prism/flow";
import fortran from "react-syntax-highlighter/dist/cjs/languages/prism/fortran";
import fsharp from "react-syntax-highlighter/dist/cjs/languages/prism/fsharp";
import ftl from "react-syntax-highlighter/dist/cjs/languages/prism/ftl";
import gap from "react-syntax-highlighter/dist/cjs/languages/prism/gap";
import gcode from "react-syntax-highlighter/dist/cjs/languages/prism/gcode";
import gdscript from "react-syntax-highlighter/dist/cjs/languages/prism/gdscript";
import gedcom from "react-syntax-highlighter/dist/cjs/languages/prism/gedcom";
import gherkin from "react-syntax-highlighter/dist/cjs/languages/prism/gherkin";
import git from "react-syntax-highlighter/dist/cjs/languages/prism/git";
import glsl from "react-syntax-highlighter/dist/cjs/languages/prism/glsl";
import gml from "react-syntax-highlighter/dist/cjs/languages/prism/gml";
import gn from "react-syntax-highlighter/dist/cjs/languages/prism/gn";
import go from "react-syntax-highlighter/dist/cjs/languages/prism/go";
import graphql from "react-syntax-highlighter/dist/cjs/languages/prism/graphql";
import groovy from "react-syntax-highlighter/dist/cjs/languages/prism/groovy";
import haml from "react-syntax-highlighter/dist/cjs/languages/prism/haml";
import handlebars from "react-syntax-highlighter/dist/cjs/languages/prism/handlebars";
import haskell from "react-syntax-highlighter/dist/cjs/languages/prism/haskell";
import haxe from "react-syntax-highlighter/dist/cjs/languages/prism/haxe";
import hcl from "react-syntax-highlighter/dist/cjs/languages/prism/hcl";
import hlsl from "react-syntax-highlighter/dist/cjs/languages/prism/hlsl";
import hoon from "react-syntax-highlighter/dist/cjs/languages/prism/hoon";
import hpkp from "react-syntax-highlighter/dist/cjs/languages/prism/hpkp";
import hsts from "react-syntax-highlighter/dist/cjs/languages/prism/hsts";
import http from "react-syntax-highlighter/dist/cjs/languages/prism/http";
import ichigojam from "react-syntax-highlighter/dist/cjs/languages/prism/ichigojam";
import icon from "react-syntax-highlighter/dist/cjs/languages/prism/icon";
import idris from "react-syntax-highlighter/dist/cjs/languages/prism/idris";
import iecst from "react-syntax-highlighter/dist/cjs/languages/prism/iecst";
import ignore from "react-syntax-highlighter/dist/cjs/languages/prism/ignore";
import inform7 from "react-syntax-highlighter/dist/cjs/languages/prism/inform7";
import ini from "react-syntax-highlighter/dist/cjs/languages/prism/ini";
import io from "react-syntax-highlighter/dist/cjs/languages/prism/io";
import j from "react-syntax-highlighter/dist/cjs/languages/prism/j";
import java from "react-syntax-highlighter/dist/cjs/languages/prism/java";
import javadoc from "react-syntax-highlighter/dist/cjs/languages/prism/javadoc";
import javadoclike from "react-syntax-highlighter/dist/cjs/languages/prism/javadoclike";
import javascript from "react-syntax-highlighter/dist/cjs/languages/prism/javascript";
import javastacktrace from "react-syntax-highlighter/dist/cjs/languages/prism/javastacktrace";
import jexl from "react-syntax-highlighter/dist/cjs/languages/prism/jexl";
import jolie from "react-syntax-highlighter/dist/cjs/languages/prism/jolie";
import jq from "react-syntax-highlighter/dist/cjs/languages/prism/jq";
import jsdoc from "react-syntax-highlighter/dist/cjs/languages/prism/jsdoc";
import json from "react-syntax-highlighter/dist/cjs/languages/prism/json";
import json5 from "react-syntax-highlighter/dist/cjs/languages/prism/json5";
import jsonp from "react-syntax-highlighter/dist/cjs/languages/prism/jsonp";
import jsstacktrace from "react-syntax-highlighter/dist/cjs/languages/prism/jsstacktrace";
import jsx from "react-syntax-highlighter/dist/cjs/languages/prism/jsx";
import julia from "react-syntax-highlighter/dist/cjs/languages/prism/julia";
import keepalived from "react-syntax-highlighter/dist/cjs/languages/prism/keepalived";
import keyman from "react-syntax-highlighter/dist/cjs/languages/prism/keyman";
import kotlin from "react-syntax-highlighter/dist/cjs/languages/prism/kotlin";
import kumir from "react-syntax-highlighter/dist/cjs/languages/prism/kumir";
import kusto from "react-syntax-highlighter/dist/cjs/languages/prism/kusto";
import latex from "react-syntax-highlighter/dist/cjs/languages/prism/latex";
import latte from "react-syntax-highlighter/dist/cjs/languages/prism/latte";
import less from "react-syntax-highlighter/dist/cjs/languages/prism/less";
import lilypond from "react-syntax-highlighter/dist/cjs/languages/prism/lilypond";
import liquid from "react-syntax-highlighter/dist/cjs/languages/prism/liquid";
import lisp from "react-syntax-highlighter/dist/cjs/languages/prism/lisp";
import livescript from "react-syntax-highlighter/dist/cjs/languages/prism/livescript";
import llvm from "react-syntax-highlighter/dist/cjs/languages/prism/llvm";
import log from "react-syntax-highlighter/dist/cjs/languages/prism/log";
import lolcode from "react-syntax-highlighter/dist/cjs/languages/prism/lolcode";
import lua from "react-syntax-highlighter/dist/cjs/languages/prism/lua";
import magma from "react-syntax-highlighter/dist/cjs/languages/prism/magma";
import makefile from "react-syntax-highlighter/dist/cjs/languages/prism/makefile";
import markdown from "react-syntax-highlighter/dist/cjs/languages/prism/markdown";
import markup from "react-syntax-highlighter/dist/cjs/languages/prism/markup";
import matlab from "react-syntax-highlighter/dist/cjs/languages/prism/matlab";
import maxscript from "react-syntax-highlighter/dist/cjs/languages/prism/maxscript";
import mel from "react-syntax-highlighter/dist/cjs/languages/prism/mel";
import mermaid from "react-syntax-highlighter/dist/cjs/languages/prism/mermaid";
import mizar from "react-syntax-highlighter/dist/cjs/languages/prism/mizar";
import mongodb from "react-syntax-highlighter/dist/cjs/languages/prism/mongodb";
import monkey from "react-syntax-highlighter/dist/cjs/languages/prism/monkey";
import moonscript from "react-syntax-highlighter/dist/cjs/languages/prism/moonscript";
import n1ql from "react-syntax-highlighter/dist/cjs/languages/prism/n1ql";
import n4js from "react-syntax-highlighter/dist/cjs/languages/prism/n4js";
import naniscript from "react-syntax-highlighter/dist/cjs/languages/prism/naniscript";
import nasm from "react-syntax-highlighter/dist/cjs/languages/prism/nasm";
import neon from "react-syntax-highlighter/dist/cjs/languages/prism/neon";
import nevod from "react-syntax-highlighter/dist/cjs/languages/prism/nevod";
import nginx from "react-syntax-highlighter/dist/cjs/languages/prism/nginx";
import nim from "react-syntax-highlighter/dist/cjs/languages/prism/nim";
import nix from "react-syntax-highlighter/dist/cjs/languages/prism/nix";
import nsis from "react-syntax-highlighter/dist/cjs/languages/prism/nsis";
import objectivec from "react-syntax-highlighter/dist/cjs/languages/prism/objectivec";
import ocaml from "react-syntax-highlighter/dist/cjs/languages/prism/ocaml";
import opencl from "react-syntax-highlighter/dist/cjs/languages/prism/opencl";
import openqasm from "react-syntax-highlighter/dist/cjs/languages/prism/openqasm";
import oz from "react-syntax-highlighter/dist/cjs/languages/prism/oz";
import parigp from "react-syntax-highlighter/dist/cjs/languages/prism/parigp";
import parser from "react-syntax-highlighter/dist/cjs/languages/prism/parser";
import pascal from "react-syntax-highlighter/dist/cjs/languages/prism/pascal";
import pascaligo from "react-syntax-highlighter/dist/cjs/languages/prism/pascaligo";
import pcaxis from "react-syntax-highlighter/dist/cjs/languages/prism/pcaxis";
import peoplecode from "react-syntax-highlighter/dist/cjs/languages/prism/peoplecode";
import perl from "react-syntax-highlighter/dist/cjs/languages/prism/perl";
import php from "react-syntax-highlighter/dist/cjs/languages/prism/php";
import phpdoc from "react-syntax-highlighter/dist/cjs/languages/prism/phpdoc";
import plsql from "react-syntax-highlighter/dist/cjs/languages/prism/plsql";
import powerquery from "react-syntax-highlighter/dist/cjs/languages/prism/powerquery";
import powershell from "react-syntax-highlighter/dist/cjs/languages/prism/powershell";
import processing from "react-syntax-highlighter/dist/cjs/languages/prism/processing";
import prolog from "react-syntax-highlighter/dist/cjs/languages/prism/prolog";
import promql from "react-syntax-highlighter/dist/cjs/languages/prism/promql";
import properties from "react-syntax-highlighter/dist/cjs/languages/prism/properties";
import protobuf from "react-syntax-highlighter/dist/cjs/languages/prism/protobuf";
import psl from "react-syntax-highlighter/dist/cjs/languages/prism/psl";
import pug from "react-syntax-highlighter/dist/cjs/languages/prism/pug";
import puppet from "react-syntax-highlighter/dist/cjs/languages/prism/puppet";
import pure from "react-syntax-highlighter/dist/cjs/languages/prism/pure";
import purebasic from "react-syntax-highlighter/dist/cjs/languages/prism/purebasic";
import purescript from "react-syntax-highlighter/dist/cjs/languages/prism/purescript";
import python from "react-syntax-highlighter/dist/cjs/languages/prism/python";
import q from "react-syntax-highlighter/dist/cjs/languages/prism/q";
import qml from "react-syntax-highlighter/dist/cjs/languages/prism/qml";
import qore from "react-syntax-highlighter/dist/cjs/languages/prism/qore";
import qsharp from "react-syntax-highlighter/dist/cjs/languages/prism/qsharp";
import r from "react-syntax-highlighter/dist/cjs/languages/prism/r";
import racket from "react-syntax-highlighter/dist/cjs/languages/prism/racket";
import reason from "react-syntax-highlighter/dist/cjs/languages/prism/reason";
import regex from "react-syntax-highlighter/dist/cjs/languages/prism/regex";
import rego from "react-syntax-highlighter/dist/cjs/languages/prism/rego";
import renpy from "react-syntax-highlighter/dist/cjs/languages/prism/renpy";
import rest from "react-syntax-highlighter/dist/cjs/languages/prism/rest";
import rip from "react-syntax-highlighter/dist/cjs/languages/prism/rip";
import roboconf from "react-syntax-highlighter/dist/cjs/languages/prism/roboconf";
import robotframework from "react-syntax-highlighter/dist/cjs/languages/prism/robotframework";
import ruby from "react-syntax-highlighter/dist/cjs/languages/prism/ruby";
import rust from "react-syntax-highlighter/dist/cjs/languages/prism/rust";
import sas from "react-syntax-highlighter/dist/cjs/languages/prism/sas";
import sass from "react-syntax-highlighter/dist/cjs/languages/prism/sass";
import scala from "react-syntax-highlighter/dist/cjs/languages/prism/scala";
import scheme from "react-syntax-highlighter/dist/cjs/languages/prism/scheme";
import scss from "react-syntax-highlighter/dist/cjs/languages/prism/scss";
import smali from "react-syntax-highlighter/dist/cjs/languages/prism/smali";
import smalltalk from "react-syntax-highlighter/dist/cjs/languages/prism/smalltalk";
import smarty from "react-syntax-highlighter/dist/cjs/languages/prism/smarty";
import sml from "react-syntax-highlighter/dist/cjs/languages/prism/sml";
import solidity from "react-syntax-highlighter/dist/cjs/languages/prism/solidity";
import soy from "react-syntax-highlighter/dist/cjs/languages/prism/soy";
import sparql from "react-syntax-highlighter/dist/cjs/languages/prism/sparql";
import sqf from "react-syntax-highlighter/dist/cjs/languages/prism/sqf";
import sql from "react-syntax-highlighter/dist/cjs/languages/prism/sql";
import squirrel from "react-syntax-highlighter/dist/cjs/languages/prism/squirrel";
import stan from "react-syntax-highlighter/dist/cjs/languages/prism/stan";
import stylus from "react-syntax-highlighter/dist/cjs/languages/prism/stylus";
import swift from "react-syntax-highlighter/dist/cjs/languages/prism/swift";
import systemd from "react-syntax-highlighter/dist/cjs/languages/prism/systemd";
import tap from "react-syntax-highlighter/dist/cjs/languages/prism/tap";
import tcl from "react-syntax-highlighter/dist/cjs/languages/prism/tcl";
import textile from "react-syntax-highlighter/dist/cjs/languages/prism/textile";
import toml from "react-syntax-highlighter/dist/cjs/languages/prism/toml";
import tremor from "react-syntax-highlighter/dist/cjs/languages/prism/tremor";
import tsx from "react-syntax-highlighter/dist/cjs/languages/prism/tsx";
import tt2 from "react-syntax-highlighter/dist/cjs/languages/prism/tt2";
import turtle from "react-syntax-highlighter/dist/cjs/languages/prism/turtle";
import twig from "react-syntax-highlighter/dist/cjs/languages/prism/twig";
import typescript from "react-syntax-highlighter/dist/cjs/languages/prism/typescript";
import typoscript from "react-syntax-highlighter/dist/cjs/languages/prism/typoscript";
import unrealscript from "react-syntax-highlighter/dist/cjs/languages/prism/unrealscript";
import uorazor from "react-syntax-highlighter/dist/cjs/languages/prism/uorazor";
import uri from "react-syntax-highlighter/dist/cjs/languages/prism/uri";
import v from "react-syntax-highlighter/dist/cjs/languages/prism/v";
import vala from "react-syntax-highlighter/dist/cjs/languages/prism/vala";
import vbnet from "react-syntax-highlighter/dist/cjs/languages/prism/vbnet";
import velocity from "react-syntax-highlighter/dist/cjs/languages/prism/velocity";
import verilog from "react-syntax-highlighter/dist/cjs/languages/prism/verilog";
import vhdl from "react-syntax-highlighter/dist/cjs/languages/prism/vhdl";
import vim from "react-syntax-highlighter/dist/cjs/languages/prism/vim";
import warpscript from "react-syntax-highlighter/dist/cjs/languages/prism/warpscript";
import wasm from "react-syntax-highlighter/dist/cjs/languages/prism/wasm";
import wiki from "react-syntax-highlighter/dist/cjs/languages/prism/wiki";
import wolfram from "react-syntax-highlighter/dist/cjs/languages/prism/wolfram";
import wren from "react-syntax-highlighter/dist/cjs/languages/prism/wren";
import xeora from "react-syntax-highlighter/dist/cjs/languages/prism/xeora";
import xojo from "react-syntax-highlighter/dist/cjs/languages/prism/xojo";
import xquery from "react-syntax-highlighter/dist/cjs/languages/prism/xquery";
import yaml from "react-syntax-highlighter/dist/cjs/languages/prism/yaml";
import yang from "react-syntax-highlighter/dist/cjs/languages/prism/yang";
import zig from "react-syntax-highlighter/dist/cjs/languages/prism/zig";
import rangeParser from "parse-numeric-range";

SyntaxHighlighter.registerLanguage("abnf", abnf);
SyntaxHighlighter.registerLanguage("actionscript", actionscript);
SyntaxHighlighter.registerLanguage("ada", ada);
SyntaxHighlighter.registerLanguage("agda", agda);
SyntaxHighlighter.registerLanguage("al", al);
SyntaxHighlighter.registerLanguage("antlr4", antlr4);
SyntaxHighlighter.registerLanguage("apacheconf", apacheconf);
SyntaxHighlighter.registerLanguage("apex", apex);
SyntaxHighlighter.registerLanguage("apl", apl);
SyntaxHighlighter.registerLanguage("applescript", applescript);
SyntaxHighlighter.registerLanguage("aql", aql);
SyntaxHighlighter.registerLanguage("arduino", arduino);
SyntaxHighlighter.registerLanguage("arff", arff);
SyntaxHighlighter.registerLanguage("asciidoc", asciidoc);
SyntaxHighlighter.registerLanguage("asm6502", asm6502);
SyntaxHighlighter.registerLanguage("asmatmel", asmatmel);
SyntaxHighlighter.registerLanguage("aspnet", aspnet);
SyntaxHighlighter.registerLanguage("autohotkey", autohotkey);
SyntaxHighlighter.registerLanguage("autoit", autoit);
SyntaxHighlighter.registerLanguage("avisynth", avisynth);
SyntaxHighlighter.registerLanguage("bash", bash);
SyntaxHighlighter.registerLanguage("basic", basic);
SyntaxHighlighter.registerLanguage("batch", batch);
SyntaxHighlighter.registerLanguage("bbcode", bbcode);
SyntaxHighlighter.registerLanguage("bicep", bicep);
SyntaxHighlighter.registerLanguage("birb", birb);
SyntaxHighlighter.registerLanguage("bison", bison);
SyntaxHighlighter.registerLanguage("bnf", bnf);
SyntaxHighlighter.registerLanguage("brainfuck", brainfuck);
SyntaxHighlighter.registerLanguage("brightscript", brightscript);
SyntaxHighlighter.registerLanguage("bro", bro);
SyntaxHighlighter.registerLanguage("bsl", bsl);
SyntaxHighlighter.registerLanguage("c", c);
SyntaxHighlighter.registerLanguage("cfscript", cfscript);
SyntaxHighlighter.registerLanguage("chaiscript", chaiscript);
SyntaxHighlighter.registerLanguage("cil", cil);
SyntaxHighlighter.registerLanguage("clike", clike);
SyntaxHighlighter.registerLanguage("clojure", clojure);
SyntaxHighlighter.registerLanguage("cmake", cmake);
SyntaxHighlighter.registerLanguage("cobol", cobol);
SyntaxHighlighter.registerLanguage("coffeescript", coffeescript);
SyntaxHighlighter.registerLanguage("concurnas", concurnas);
SyntaxHighlighter.registerLanguage("coq", coq);
SyntaxHighlighter.registerLanguage("cpp", cpp);
SyntaxHighlighter.registerLanguage("crystal", crystal);
SyntaxHighlighter.registerLanguage("csharp", csharp);
SyntaxHighlighter.registerLanguage("cshtml", cshtml);
SyntaxHighlighter.registerLanguage("csp", csp);
SyntaxHighlighter.registerLanguage("css", css);
SyntaxHighlighter.registerLanguage("csv", csv);
SyntaxHighlighter.registerLanguage("cypher", cypher);
SyntaxHighlighter.registerLanguage("d", d);
SyntaxHighlighter.registerLanguage("dart", dart);
SyntaxHighlighter.registerLanguage("dataweave", dataweave);
SyntaxHighlighter.registerLanguage("dax", dax);
SyntaxHighlighter.registerLanguage("dhall", dhall);
SyntaxHighlighter.registerLanguage("diff", diff);
SyntaxHighlighter.registerLanguage("django", django);
SyntaxHighlighter.registerLanguage("docker", docker);
SyntaxHighlighter.registerLanguage("dot", dot);
SyntaxHighlighter.registerLanguage("ebnf", ebnf);
SyntaxHighlighter.registerLanguage("editorconfig", editorconfig);
SyntaxHighlighter.registerLanguage("eiffel", eiffel);
SyntaxHighlighter.registerLanguage("ejs", ejs);
SyntaxHighlighter.registerLanguage("elixir", elixir);
SyntaxHighlighter.registerLanguage("elm", elm);
SyntaxHighlighter.registerLanguage("erb", erb);
SyntaxHighlighter.registerLanguage("erlang", erlang);
SyntaxHighlighter.registerLanguage("etlua", etlua);
SyntaxHighlighter.registerLanguage("factor", factor);
SyntaxHighlighter.registerLanguage("flow", flow);
SyntaxHighlighter.registerLanguage("fortran", fortran);
SyntaxHighlighter.registerLanguage("fsharp", fsharp);
SyntaxHighlighter.registerLanguage("ftl", ftl);
SyntaxHighlighter.registerLanguage("gap", gap);
SyntaxHighlighter.registerLanguage("gcode", gcode);
SyntaxHighlighter.registerLanguage("gdscript", gdscript);
SyntaxHighlighter.registerLanguage("gedcom", gedcom);
SyntaxHighlighter.registerLanguage("gherkin", gherkin);
SyntaxHighlighter.registerLanguage("git", git);
SyntaxHighlighter.registerLanguage("glsl", glsl);
SyntaxHighlighter.registerLanguage("gml", gml);
SyntaxHighlighter.registerLanguage("gn", gn);
SyntaxHighlighter.registerLanguage("go", go);
SyntaxHighlighter.registerLanguage("graphql", graphql);
SyntaxHighlighter.registerLanguage("groovy", groovy);
SyntaxHighlighter.registerLanguage("haml", haml);
SyntaxHighlighter.registerLanguage("handlebars", handlebars);
SyntaxHighlighter.registerLanguage("haskell", haskell);
SyntaxHighlighter.registerLanguage("haxe", haxe);
SyntaxHighlighter.registerLanguage("hcl", hcl);
SyntaxHighlighter.registerLanguage("hlsl", hlsl);
SyntaxHighlighter.registerLanguage("hoon", hoon);
SyntaxHighlighter.registerLanguage("hpkp", hpkp);
SyntaxHighlighter.registerLanguage("hsts", hsts);
SyntaxHighlighter.registerLanguage("http", http);
SyntaxHighlighter.registerLanguage("ichigojam", ichigojam);
SyntaxHighlighter.registerLanguage("icon", icon);
SyntaxHighlighter.registerLanguage("idris", idris);
SyntaxHighlighter.registerLanguage("iecst", iecst);
SyntaxHighlighter.registerLanguage("ignore", ignore);
SyntaxHighlighter.registerLanguage("inform7", inform7);
SyntaxHighlighter.registerLanguage("ini", ini);
SyntaxHighlighter.registerLanguage("io", io);
SyntaxHighlighter.registerLanguage("j", j);
SyntaxHighlighter.registerLanguage("java", java);
SyntaxHighlighter.registerLanguage("javadoc", javadoc);
SyntaxHighlighter.registerLanguage("javadoclike", javadoclike);
SyntaxHighlighter.registerLanguage("javascript", javascript);
SyntaxHighlighter.registerLanguage("javastacktrace", javastacktrace);
SyntaxHighlighter.registerLanguage("jexl", jexl);
SyntaxHighlighter.registerLanguage("jolie", jolie);
SyntaxHighlighter.registerLanguage("jq", jq);
SyntaxHighlighter.registerLanguage("jsdoc", jsdoc);
SyntaxHighlighter.registerLanguage("json", json);
SyntaxHighlighter.registerLanguage("json5", json5);
SyntaxHighlighter.registerLanguage("jsonp", jsonp);
SyntaxHighlighter.registerLanguage("jsstacktrace", jsstacktrace);
SyntaxHighlighter.registerLanguage("jsx", jsx);
SyntaxHighlighter.registerLanguage("julia", julia);
SyntaxHighlighter.registerLanguage("keepalived", keepalived);
SyntaxHighlighter.registerLanguage("keyman", keyman);
SyntaxHighlighter.registerLanguage("kotlin", kotlin);
SyntaxHighlighter.registerLanguage("kumir", kumir);
SyntaxHighlighter.registerLanguage("kusto", kusto);
SyntaxHighlighter.registerLanguage("latex", latex);
SyntaxHighlighter.registerLanguage("latte", latte);
SyntaxHighlighter.registerLanguage("less", less);
SyntaxHighlighter.registerLanguage("lilypond", lilypond);
SyntaxHighlighter.registerLanguage("liquid", liquid);
SyntaxHighlighter.registerLanguage("lisp", lisp);
SyntaxHighlighter.registerLanguage("livescript", livescript);
SyntaxHighlighter.registerLanguage("llvm", llvm);
SyntaxHighlighter.registerLanguage("log", log);
SyntaxHighlighter.registerLanguage("lolcode", lolcode);
SyntaxHighlighter.registerLanguage("lua", lua);
SyntaxHighlighter.registerLanguage("magma", magma);
SyntaxHighlighter.registerLanguage("makefile", makefile);
SyntaxHighlighter.registerLanguage("markdown", markdown);
SyntaxHighlighter.registerLanguage("markup", markup);
SyntaxHighlighter.registerLanguage("matlab", matlab);
SyntaxHighlighter.registerLanguage("maxscript", maxscript);
SyntaxHighlighter.registerLanguage("mel", mel);
SyntaxHighlighter.registerLanguage("mermaid", mermaid);
SyntaxHighlighter.registerLanguage("mizar", mizar);
SyntaxHighlighter.registerLanguage("mongodb", mongodb);
SyntaxHighlighter.registerLanguage("monkey", monkey);
SyntaxHighlighter.registerLanguage("moonscript", moonscript);
SyntaxHighlighter.registerLanguage("n1ql", n1ql);
SyntaxHighlighter.registerLanguage("n4js", n4js);
SyntaxHighlighter.registerLanguage("naniscript", naniscript);
SyntaxHighlighter.registerLanguage("nasm", nasm);
SyntaxHighlighter.registerLanguage("neon", neon);
SyntaxHighlighter.registerLanguage("nevod", nevod);
SyntaxHighlighter.registerLanguage("nginx", nginx);
SyntaxHighlighter.registerLanguage("nim", nim);
SyntaxHighlighter.registerLanguage("nix", nix);
SyntaxHighlighter.registerLanguage("nsis", nsis);
SyntaxHighlighter.registerLanguage("objectivec", objectivec);
SyntaxHighlighter.registerLanguage("ocaml", ocaml);
SyntaxHighlighter.registerLanguage("opencl", opencl);
SyntaxHighlighter.registerLanguage("openqasm", openqasm);
SyntaxHighlighter.registerLanguage("oz", oz);
SyntaxHighlighter.registerLanguage("parigp", parigp);
SyntaxHighlighter.registerLanguage("parser", parser);
SyntaxHighlighter.registerLanguage("pascal", pascal);
SyntaxHighlighter.registerLanguage("pascaligo", pascaligo);
SyntaxHighlighter.registerLanguage("pcaxis", pcaxis);
SyntaxHighlighter.registerLanguage("peoplecode", peoplecode);
SyntaxHighlighter.registerLanguage("perl", perl);
SyntaxHighlighter.registerLanguage("php", php);
SyntaxHighlighter.registerLanguage("phpdoc", phpdoc);
SyntaxHighlighter.registerLanguage("plsql", plsql);
SyntaxHighlighter.registerLanguage("powerquery", powerquery);
SyntaxHighlighter.registerLanguage("powershell", powershell);
SyntaxHighlighter.registerLanguage("processing", processing);
SyntaxHighlighter.registerLanguage("prolog", prolog);
SyntaxHighlighter.registerLanguage("promql", promql);
SyntaxHighlighter.registerLanguage("properties", properties);
SyntaxHighlighter.registerLanguage("protobuf", protobuf);
SyntaxHighlighter.registerLanguage("psl", psl);
SyntaxHighlighter.registerLanguage("pug", pug);
SyntaxHighlighter.registerLanguage("puppet", puppet);
SyntaxHighlighter.registerLanguage("pure", pure);
SyntaxHighlighter.registerLanguage("purebasic", purebasic);
SyntaxHighlighter.registerLanguage("purescript", purescript);
SyntaxHighlighter.registerLanguage("python", python);
SyntaxHighlighter.registerLanguage("q", q);
SyntaxHighlighter.registerLanguage("qml", qml);
SyntaxHighlighter.registerLanguage("qore", qore);
SyntaxHighlighter.registerLanguage("qsharp", qsharp);
SyntaxHighlighter.registerLanguage("r", r);
SyntaxHighlighter.registerLanguage("racket", racket);
SyntaxHighlighter.registerLanguage("reason", reason);
SyntaxHighlighter.registerLanguage("regex", regex);
SyntaxHighlighter.registerLanguage("rego", rego);
SyntaxHighlighter.registerLanguage("renpy", renpy);
SyntaxHighlighter.registerLanguage("rest", rest);
SyntaxHighlighter.registerLanguage("rip", rip);
SyntaxHighlighter.registerLanguage("roboconf", roboconf);
SyntaxHighlighter.registerLanguage("robotframework", robotframework);
SyntaxHighlighter.registerLanguage("ruby", ruby);
SyntaxHighlighter.registerLanguage("rust", rust);
SyntaxHighlighter.registerLanguage("sas", sas);
SyntaxHighlighter.registerLanguage("sass", sass);
SyntaxHighlighter.registerLanguage("scala", scala);
SyntaxHighlighter.registerLanguage("scheme", scheme);
SyntaxHighlighter.registerLanguage("scss", scss);
SyntaxHighlighter.registerLanguage("smali", smali);
SyntaxHighlighter.registerLanguage("smalltalk", smalltalk);
SyntaxHighlighter.registerLanguage("smarty", smarty);
SyntaxHighlighter.registerLanguage("sml", sml);
SyntaxHighlighter.registerLanguage("solidity", solidity);
SyntaxHighlighter.registerLanguage("soy", soy);
SyntaxHighlighter.registerLanguage("sparql", sparql);
SyntaxHighlighter.registerLanguage("sqf", sqf);
SyntaxHighlighter.registerLanguage("sql", sql);
SyntaxHighlighter.registerLanguage("squirrel", squirrel);
SyntaxHighlighter.registerLanguage("stan", stan);
SyntaxHighlighter.registerLanguage("stylus", stylus);
SyntaxHighlighter.registerLanguage("swift", swift);
SyntaxHighlighter.registerLanguage("systemd", systemd);
SyntaxHighlighter.registerLanguage("tap", tap);
SyntaxHighlighter.registerLanguage("tcl", tcl);
SyntaxHighlighter.registerLanguage("textile", textile);
SyntaxHighlighter.registerLanguage("toml", toml);
SyntaxHighlighter.registerLanguage("tremor", tremor);
SyntaxHighlighter.registerLanguage("tsx", tsx);
SyntaxHighlighter.registerLanguage("tt2", tt2);
SyntaxHighlighter.registerLanguage("turtle", turtle);
SyntaxHighlighter.registerLanguage("twig", twig);
SyntaxHighlighter.registerLanguage("typescript", typescript);
SyntaxHighlighter.registerLanguage("typoscript", typoscript);
SyntaxHighlighter.registerLanguage("unrealscript", unrealscript);
SyntaxHighlighter.registerLanguage("uorazor", uorazor);
SyntaxHighlighter.registerLanguage("uri", uri);
SyntaxHighlighter.registerLanguage("v", v);
SyntaxHighlighter.registerLanguage("vala", vala);
SyntaxHighlighter.registerLanguage("vbnet", vbnet);
SyntaxHighlighter.registerLanguage("velocity", velocity);
SyntaxHighlighter.registerLanguage("verilog", verilog);
SyntaxHighlighter.registerLanguage("vhdl", vhdl);
SyntaxHighlighter.registerLanguage("vim", vim);
SyntaxHighlighter.registerLanguage("warpscript", warpscript);
SyntaxHighlighter.registerLanguage("wasm", wasm);
SyntaxHighlighter.registerLanguage("wiki", wiki);
SyntaxHighlighter.registerLanguage("wolfram", wolfram);
SyntaxHighlighter.registerLanguage("wren", wren);
SyntaxHighlighter.registerLanguage("xeora", xeora);
SyntaxHighlighter.registerLanguage("xojo", xojo);
SyntaxHighlighter.registerLanguage("xquery", xquery);
SyntaxHighlighter.registerLanguage("yaml", yaml);
SyntaxHighlighter.registerLanguage("yang", yang);
SyntaxHighlighter.registerLanguage("zig", zig);

const SyntaxHighlightForMarkdown = {
  code({ node, inline, className, ...props }) {
    const match = /language-(\w+)/.exec(className || "");
    const hasMeta = node?.data?.meta;

    const applyHighlights = (applyHighlights) => {
      if (hasMeta) {
        const RE = /{([\d,-]+)}/;
        const metadata = node.data.meta?.replace(/\s/g, "");
        const strlineNumbers = RE?.test(metadata) ? RE?.exec(metadata)[1] : "0";
        const highlightLines = rangeParser(strlineNumbers);
        const highlight = highlightLines;
        const data = highlight.includes(applyHighlights) ? "highlight" : null;
        return { data };
      } else {
        return {};
      }
    };

    return match ? (
      <SyntaxHighlighter
        style={darcula}
        language={match[1]}
        PreTag="div"
        className="codeStyle"
        showLineNumbers={true}
        wrapLines={hasMeta ? true : false}
        useInlineStyles={true}
        lineProps={applyHighlights}
        {...props}
      />
    ) : (
      <code className={className} {...props} />
    );
  },
};

export default SyntaxHighlightForMarkdown;
